verbose: false
debug: false

database:
  host: mongodb://localhost:27017
  name: anywhere
  user: admin
  pass: password

datastore:
  host: http://localhost:9001
  name: anywhere
  user: admin
  pass: password

server:
  port: 8042
  allow_origins:
    - http://localhost:3000
