name: Build Executable

on:
  workflow_call:

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - run: make

      - uses: actions/upload-artifact@v3
        with:
          name: anywhere.zip
          path: ./bin
