name: Build

on:
  push:
    branches:
      - master

env:
  image: public.ecr.aws/axatol/anywhere

jobs:
  build-backend:
    name: Build backend

    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

      - name: Pull previous version
        run: docker pull ${{ env.image }}:latest

      - name: Tag previous verion
        run: docker tag ${{ env.image }}:latest ${{ env.image }}:previous

      - name: Build new version
        run: docker build -t ${{ env.image }}:latest .

      - name: Push new version
        run: docker push ${{ env.image }}:latest

      - name: Push previous version
        run: docker push ${{ env.image }}:previous

      - uses: hans-m-song/actions/prune-ecr-repository@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          repository-name: anywhere
