on:
  push:
    branches:
      - master

jobs:
  build-executable:
    uses: ./.github/workflows/_build-executable.yml

  build-image:
    uses: ./.github/workflows/_build-image.yml
    secrets: inherit
