on:
  push:
    branches:
      - master

jobs:
  build-executable:
    uses: ./.github/workflows/_build-executable.yml

  build-slim-image:
    needs: build-executable
    uses: ./.github/workflows/_build-slim-image.yml
    secrets: inherit
